server:
  port: 9000
  servlet:
    context-path: /api

spring.mail:
  from: Logius
  debug: false
  host: smtp.gmail.com
  port: 587
  username: facultiesgit@gmail.com
  password: z200198l192ws
  transport.protocol: smtp
  properties.mail.smtp:
    auth: true
    starttls.enable: true

spring:
  jpa:
    properties:
      hibernate.current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext
      charSet: UTF-8
      hibernate.dialect: org.hibernate.dialect.MySQLDialect

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/logius
    username: logius
    password: logius
#    properties:
#      initial-size: 1
#      maxIdle: 5
#      minIdle: 5
#      initialSize: 5
database:
  maxWaitForConnection: 1s
  validationQuery: "/* MyApplication Health Check */ SELECT 1"
  # the minimum number of connections to keep open
  minSize: 8
  # the maximum number of connections to keep open
  maxSize: 32
  # whether or not idle connections should be validated
  checkConnectionWhileIdle: true
  checkConnectionOnReturn: true
  checkConnectionOnBorrow: true
heritrix:
  configTemplatePath: /home/evgeny/dl/logiuss/verapdf-crawler/LogiusWebApp/src/main/resources/sample_configuration.cxml
  url: https://localhost:8443/
  login: admin
  password: logius
  logiusAppUrl: http://localhost:8080
  jobsFolder: /home/evgeny/heritrix/jobs/
reports:
  odsTemplatePath: /home/evgeny/dl/logiuss/verapdf-crawler/LogiusWebApp/src/main/resources/sample_report.ods
  notificationEmails: temp.email@domain.com,temp2email@domain.com
  odsTempFolder: /home/evgeny/Documents/Logius/temp/ods
bing:
  baseTempFolder: /home/evgeny/Documents/Logius/temp/bing
  apiKey: someApiKey
pdfProcessors:
  pdfwamChecker: /home/evgeny/Documents/Logius/pdfwam/pdfchecker.py
veraPDFService:
  url: http://localhost:8100
  verapdfPath: /home/evgeny/dl/logiuss/verapdf/verapdf.sh
  verapdfErrors: /home/evgeny/Documents/Logius/logs/verapdfErrors.log

