server:
  applicationConnectors:
  - type: http 
    port: 8100
  adminConnectors:
  - type: http
    port: 8101
verapdfPath: /home/anton/verapdf/verapdf
verapdfErrors: /home/anton/Documents/Logius/logs/verapdfErrors.log
logiusUrl: http://localhost:9000/api
logging:
  level: WARN
  loggers:
    org.verapdf.service:
      level: INFO
  appenders:
    - type: file
      currentLogFilename: /home/anton/Documents/Logius/logs/verapdfService.log
      archive: true
      archivedLogFilenamePattern: /home/anton/Documents/Logius/logs/verapdfService-%d.log
      archivedFileCount: 10
