# meta file for apt
---
galaxy_info:
  author: Carl Wilson
  company: The Open Preservation Foundation
  description: Installs heritrix and
  license: GPL v3
  min_ansible_version: 1.9.6
  platforms:
    - name: Ubuntu
      versions:
        - precise
        - trusty
        - xenial
    - name: Debian
      versions:
        - wheezy
        - jessie
  galaxy_tags:
    - web archiving
    - web harvesting
dependencies: []
