server:
  applicationConnectors:
  - type: http 
    port: 9000
  adminConnectors:
  - type: http
    port: 9001
emailServer:
  host: smtp.gmail.com
  address: shemyanton@gmail.com	
  user: shemyanton@gmail.com	
  password: password
  port: 587
resourcePath: /home/anton/Documents/Logius/LogiusWebApp/src/main/resources/
heritrixLogin: admin
heritrixPassword: logius
verapdfPath: /home/anton/verapdf/verapdf
