server:
  applicationConnectors:
  - type: http 
    port: 9000
  adminConnectors:
  - type: http
    port: 9001
emailServer:
  host: smtp.gmail.com
  address: logiuscrawlernotifier@gmail.com	
  user: logiuscrawlernotifier@gmail.com	
  password: Logius2017
  port: 587
mysql:
  connectionString: jdbc:mysql://localhost:3306/logius?useSSL=false
  user: root
  password: anton
heritrix:
  resourcePath: /home/anton/Documents/Logius/LogiusWebApp/src/main/resources/
  url: https://localhost:8443/
  login: admin
  password: logius
veraPDFService:
  url: http://localhost:8100
logging:
  level: WARN
  loggers:
    "CustomLogger":
      additive: false
      level: INFO
      appenders:
      - type: file
        currentLogFilename: /home/anton/Documents/Logius/logs/logius.log
        archive: true
        archivedLogFilenamePattern: /home/anton/Documents/Logius/logs/logius-%d.log
        archivedFileCount: 10