# tasks file for verapdf.logius
---

- name: INCLUDE | setup
  include: setup.yml

- name: INCLUDE | heritrix
  include: heritrix.yml

- name: INCLUDE | pdfwam
  include: pdfwam.yml

- name: INCLUDE | services
  include: services.yml

- name: INCLUDE | build
  include: build.yml
