---

# Playbook to configure a logius-crawler instance
# File: ansible/site.yml


- hosts: all
  become: true
  roles:
    - { role: tschifftner.hostname }
    - { role: tersmitten.timezone }
    - { role: tersmitten.apt }

- hosts: heretrix
  become: true
  roles:
    - { role: geerlingguy.mysql }
    - { role: HanXHX.nginx }

# These task adds the Debian Jessie Backports repo for apt to allow installation
# of open JDK 8 if required
- hosts: heretrix
  become: true
  tasks:
    - name: Backports repo for Java 8 in Debian
      apt_repository:
        repo: deb http://ftp.de.debian.org/debian jessie-backports main
        state: present
    - name: installing Java 8
      apt:
        name: openjdk-8-jdk
        state: present
        default_release: jessie-backports
        update_cache: yes
    - name: correct java version selected
      alternatives:
        name: java
        path: /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java
