---

# Playbook to configure a logius-crawler instance
# File: ansible/site.yml


- hosts: all
  become: true
  roles:
    - { role: tschifftner.hostname }
    - { role: tersmitten.timezone }
    - { role: tersmitten.apt }

- hosts: heretrix
  become: true
  roles:
    - { role: geerlingguy.mysql }
    - { role: HanXHX.nginx }
    - { role: opf.heritrix }
